export const CONNECT_FACEBOOK='/facebook/connect'
export const DISCONNECT_FACEBOOK='/facebook/disconnect'
export const CONNECT_TELEGRAM='/telegram/connect'
export const DISCONNECT_TELEGRAM='/telegram/disconnect'
export const GET_PLATFORM_STATUS='/platform/status'